### ISSUE TITLE
ggdag wants me to control for latent variable

### ISSUE THREAD

**Issue by raffaem** [r-causal/ggdag#103]
With `type=all`, `ggdag_adjustment_set` plots adjustment sets that have latent variables in them:

```
#!/usr/bin/env R

library(ggdag)

dag <- dagify(
	x1 ~ x2,
	x2 ~ x3 + x4,
	x3 ~ x5,
	x4 ~ x5,
	latent = "x5",
	exposure = "x3",
	outcome = "x1"
) %>% tidy_dagitty()

ggdag_adjustment_set(dag, type="all")
```

![image](https://github.com/r-causal/ggdag/assets/54762742/07c8eee4-9559-462d-8d9b-af141dfa176a)

**Comment by malcolmbarrett** [comment]
Can you tell me more about what you were expecting?

`type` is an argument in `dagitty::adjustmentSets()`. `"all"` is described in the documentation as: "all valid adjustment sets are returned". That seems accurate to me; the sets with the latent variable ARE valid, you just can't do anything about them.

It seems like 1) this is correct and 2) if you disagree with what's happening here, you should file an issue with dagitty.

**Comment by raffaem** [comment]
Well it looks like I don't know the definition of "valid".

So how can I exclude those adjustment sets?

I came up with a code like this.

But it's only to get the adjustment sets, not to plot them.

And it looks cumbersome too.

```
get.adj.sets <- function(dag, label=T) {
	adjsets <- ggdag::dag_adjustment_sets(dag, type="all")
	# Get adjustment sets
	adjs <- unique(adjsets$data$set)
	# Remove adjustment sets with latent variables
	adjs2 <- c()
	vars.lat <- dagitty::latents(dag$dag)
	for(adj in adjs) {
		mask1 <- adjsets$data$set==adj
		mask2 <- adjsets$data$adjusted=="adjusted"
		names <- unique(adjsets$data[mask1 & mask2,][["name"]])
		include = T
		for(name in names) {
			if(name %in% vars.lat) {
				include = F
				break
			}
		}
		if(include) {
			adjs2[length(adjs2)+1] <- adj
		}
	}
	# Exit if no adjustment sets are available
	# Not to be confused with empty adjustment set
	# Notice that an empty array (c()) is null
	# i.e, is.null(c())==TRUE
	if(length(adjs2)==0) {
		return(list(no=TRUE, adjsets=list()))
	}
	# Get adjustment sets
	out <- list(no=FALSE, adjsets=list())
	for(adj in adjs2) {
		mask1 <- adjsets$data$set==adj
		mask2 <- adjsets$data$adjusted=="adjusted"
		df <- adjsets$data[mask1 & mask2,]
		if(label & ("label" %in% df)) {
			labels <- unique(df$label)
			out$adjsets[[length(out$adjsets)+1]] <- c(labels)
		}
		else {
			names <- unique(df$name)
			out$adjsets[[length(out$adjsets)+1]] <- c(names)
		}
	}
	return(out)
}
```

**Comment by malcolmbarrett** [comment]
Ok, well, IMO this is working as expected. If you disagree, I recommend filing an issue on the dagitty repo to discuss.

As with our last conversation, if you want to be doing custom things in ggdag, including manipulating the data structure, you will likely find yourself needing to use the geoms that ggdag provides directly. For this case, I recommend looking at the source code for `ggdag_adjustment_sets()` to see how to plot the data you created
