### ISSUE TITLE
remove the adjustment variable set in ggdag_adjustment_set

### ISSUE THREAD

**Issue by willizhang** [r-causal/ggdag#123]
Hi,

I would like to ask how to remove the adjustment variable set at the top of the DAG in ggdag_adjustment_set.

Thank you very much for this beautiful package.

Best wishes,
Willi

```
library(ggplot2)
library(ggdag)
theme_set(theme_dag())


coffee_dag <- dagify(cancer ~ smoking,
                     smoking ~ addictive,
                     coffee ~ addictive,
                     exposure = "coffee",
                     outcome = "cancer",
                     labels = c(
                       "coffee" = "Coffee", "cancer" = "Lung Cancer",
                       "smoking" = "Smoking", "addictive" = "Addictive \nBehavior"
                     )
) %>%
  tidy_dagitty(layout = "tree")

ggdag_adjustment_set(coffee_dag, text = FALSE, use_labels = "label", shadow = TRUE)
```

<img width="643" alt="image" src="https://github.com/r-causal/ggdag/assets/64090640/1a04c2fc-5dd2-4961-8cd4-c86b830583c0">

**Comment by malcolmbarrett** [comment]
That is a result of `facet_wrap()` (maybe a little more obvious if you look at it with the default ggplot2 theme). That makes this problem easy: remove the facet text with `theme(strip.text = element_blank())`.

If you want to do this globally, you can still use `theme_set()`: `theme_set(theme_dag() + theme(strip.text = element_blank()))`

**Comment by willizhang** [comment]
Many thanks!
