### ISSUE TITLE
Crash in case "instrument" is not valid

### ISSUE THREAD

**Issue by 875d** [r-causal/ggdag#92]
In this DAG the instrument is not valid as correlated with error term (and there's no way to render them independent).

But `ggdag_instrumental` crashes.

```
library(ggdag)

coffee_dag <- dagify(y ~ t + x1 + x2 + x4,
										 t ~ x1 + x3,
										 x2 ~ x3 + x4,
										 exposure = "t",
										 outcome = "y",
										 latent = c("x1", "x4")
) %>% tidy_dagitty()

ggdag(coffee_dag)

ggdag_instrumental(coffee_dag)
```

Here is the error message:

```
Error: Must request at least one colour from a hue palette.
In addition: Warning message:
Unknown or uninitialised column: `instrumental_name`. 
```

If the instrument is instead valid, it "works", although it returns another plot called "NA" which I don't understand what it is:

```
library(ggdag)

coffee_dag <- dagify(y ~ t + x1 + x2 + x4,
					 t ~ x1 + x3,
					 x2 ~ x3 + x4,
					exposure = "t",
					outcome = "y",
					latent = c("x1")
) %>% tidy_dagitty()

ggdag(coffee_dag)

ggdag_instrumental(coffee_dag)
```

**Comment by malcolmbarrett** [comment]
Thanks for the report! This was a double issue: some DAGs were being mangled by `node_instrumental()` and `ggdag_instrumental()` had no way to handle a DAG without IVs. Your examples should work now

**Comment by 875d** [comment]
The first example returns a single plot titled "No instrumental variables present".

The second example wants me to use x3|x2,x4 as an instrument, which looks valid.

Thanks, looks like it works now.
