### ISSUE TITLE
Plot backdoor paths only

### ISSUE THREAD

**Issue by raffaem** [r-causal/ggdag#93]
How can I use ggdag to plot backdoor paths only?

For instance, given the following code:

```
library(ggdag)

tidy_ggdag <- dagify(
	y ~ t + x1,
	t ~ x1,
	exposure = "t",
	outcome = "y"
) %>% tidy_dagitty()

ggdag_paths(tidy_ggdag) + theme_dag()
```

It plots all open paths, not only backdoor ones:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/995GY.png

**Comment by malcolmbarrett** [comment]
If you want to do something like this, the best approach is usually to use the underlying functions to manipulate and plot the DAG. In this case, what I would do is something like

``` r
library(ggdag, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE) 
library(ggplot2)
tidy_ggdag <- dagify(
  y ~ t + x1,
  t ~ x1,
  exposure = "t",
  outcome = "y"
) %>% tidy_dagitty()

tidy_ggdag |> 
  dag_paths() |> 
  filter(set != 1) |> 
  ggplot(aes(x, y, xend = xend, yend = yend)) + 
  geom_dag_point() +
  geom_dag_edges() +
  geom_dag_text() + 
  theme_dag() + 
  facet_wrap(~ set)
```

![](https://i.imgur.com/4OZ731b.png)

<sup>Created on 2023-05-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by raffaem** [comment]
Would this work if there are 2 direct paths?

**Comment by malcolmbarrett** [comment]
Sure, you just need to decide which sets to filter out

**Comment by raffaem** [comment]
But I have to do it in an automatic way. I have an arbitrary DAG and I have to plot only the backdoor paths, whatever the number of the direct paths come in. Suppose I'm making a GUI for ggdag.

**Comment by malcolmbarrett** [comment]
Well, there's not a feature in ggdag that will do that for you, although I could see a `filter_backdoor_paths` argument for `dag_paths()` and `ggdag_paths()` being useful. 

That said, I think you could probably use `dag_path()` and then figure out programmatically which sets you want. I couldn't tell you the algorithm to do that off the top of my head, but I think it's doable. 

If you have success, you can report back in a new issue (or PR if you want) for me to consider implementing a ggdag feature that does it. If you can't make headway, you can also file a feature request, but I'll have to warn you that it would probably not be immediate.
